exclude: "^docs/|/.git/|/.tox/|/media/|/.pytest_cache/|^.idea/|.node_modules/|scaffold/templates/models/"
default_install_hook_types: [pre-commit]
default_stages: [pre-commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-xml
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: check-symlinks
      - id: detect-aws-credentials
        args: [ '--allow-missing-credentials' ]
      - id: detect-private-key
        exclude: ^examples|(?:tests/ssl)/
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
      # Run the linter.
      - id: ruff
        args: [ "--fix", "--config", "pyproject.toml" ]
      # Run the formatter.
      - id: ruff-format
        args: [ "--config", "pyproject.toml" ]

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: [ ]
  submodules: false
